// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vxioekvkspefzguodyrr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4aW9la3Zrc3BlZnpndW9keXJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MjY3MzUsImV4cCI6MjA2NTIwMjczNX0.09h5hYzGpQtTNXY9g07nHWdilFJg1B_2kVik1zPGtOs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);